### ISSUE TITLE
argv[0] is empty

### ISSUE THREAD

**Issue by rgimad** [turbocat2001/kolibri-libc#4]
argv[0] is empty: https://ibb.co/LdHFynH
but it must contain path to the program

**Comment by mxlgv** [comment]
Fixed: https://github.com/turbocat2001/kolibri-libc/commit/d12b2f410e9c763ba1cbc1a1a4a268c26cdc2dcc

![2021-02-09_02-22](https://user-images.githubusercontent.com/51446645/107294063-c6945c00-6a7d-11eb-87cd-92109a4d484f.png)
