### ISSUE TITLE
undefined reference to `__udivmoddi4'

### ISSUE THREAD

**Issue by ghost** [turbocat2001/kolibri-libc#6]
```
../bin/lib/libc.a(format_print.o): In function `_ntoa_long_long':
format_print.c:(.text+0x317): undefined reference to `__udivmoddi4'
```
При сборке argtest

**Comment by ghost** [comment]
с помощью gcc

**Comment by mkostoevr** [comment]
There's two possible solutions I know: link it with libgcc or compile it with -O0

**Comment by mxlgv** [comment]
Исправлено удалением static перед функцией __udivmoddi4 в libtcc1.c.

**Comment by mkostoevr** [comment]
Compiled&builded by TCC, works fine.

![изображение](https://user-images.githubusercontent.com/26708480/107856699-fefbb780-6e3a-11eb-8514-43ecb2332250.png)

**Comment by mkostoevr** [comment]
Could anyone try this out with GCC? Compiled by GCC the library does not allow TCC to link it:

![изображение](https://user-images.githubusercontent.com/26708480/107856829-fce62880-6e3b-11eb-9470-486771e2f33f.png)

**Comment by mxlgv** [comment]
Это баг тсс или какая то неизвестная проблема. Скорее всего нам её не решить
